### ISSUE TITLE
# Update/Edit items on Events Collection

### ISSUE THREAD

**Issue by MarkyAaronYoung** [nss-evening-cohort-12/nutshell-elk#100]
## User Story
As a user, I should be able update the quantities (remove/add) individual souvenir items, show items, staff members, and food items that have been added to the event without deleting/adding them completely from Firebase.

## AC
**When** a user is authenticated
**And** on an event page
**Then** a user can click on an individual component (staff, souvenir, show, food)
**And** change the quantity. 

## Dev Notes
* Create a component to edit an entire event - src/javascripts/components/editEvent/editEvent.js
* Create individual components to edit each item on an event -```src/javascripts/components/editEventFood/editEventFood.js```
- ```src/javascripts/components/editEventStaff/editEventStaff.js```
- ```src/javascripts/components/editEventShow/editEventShow.js```
- ```src/javascripts/components/editEventSouvenirs/editEventSouvenirs.js```
* ```$('body'). on('click', '.edit-eventStaff', editEventStaff)```
* ```$('body'). on('click', '.edit-eventSouvenirs', editEventSouvenirs)```
* ```$('body'). on('click', '.edit-eventFoods', editEventFoods)```
* ```$('body').on('click', '.edit-eventShows', editEventShows)```

**Comment by bnemchak** [comment]
<img width="396" alt="Screen Shot 2020-07-24 at 5 21 23 PM" src="https://user-images.githubusercontent.com/62910336/88439975-47398680-cdd2-11ea-8795-1a397fb73747.png">

**Comment by bnemchak** [comment]
all 4 categories will look the same but with the correct words/labels

<img width="208" alt="Screen Shot 2020-07-24 at 5 23 44 PM" src="https://user-images.githubusercontent.com/62910336/88440152-c16a0b00-cdd2-11ea-9508-8bd1ce9e9619.png">
