### ISSUE TITLE
Add Price - show

### ISSUE THREAD

**Issue by bnemchak** [nss-evening-cohort-12/nutshell-elk#104]
# User
As a user, when I visit the Shows page not logged in I should see rows of cards of each available Show now including price. 
As a user, when I visit the Shows page logged in I should see rows of cards of each Show now including price.

# AC
**WHEN** the user visits the Show section of the site via the homepage
**THEN** they should only see the available Shows displayed
**AND** they will now see a price

**WHEN** the user is Logged-in they should see all of the Shows displayed
**AND** there should also be a visible option to edit the Show and delete the Show
**AND** there should be a add Show button at the top of the page
**AND** they will now see a price

## dev notes
* add price to [seed data](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/db/shows.json) on **shows.json**
```js
"price": 25,
```

* add Price to [`showCardBuilder`](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/src/javascripts/components/showBuilder/showBuilder.js#L22) on  **showBuilder.js**
```js
<h4>Event Price: ${show.price}</h4>
```

* add Price to [`noAuthShowCardBuilder`](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/src/javascripts/components/showBuilder/showBuilder.js#L50) on  **showBuilder.js**
```js
<h4> Event Price: ${show.price}</h4>
```

* add price to [`editShowForm`](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/src/javascripts/components/editShow/editShow.js#L21) form on **editShow.js**
```html 
<div class="form-group">
    <label for="editShow-price">Price</label>
    <input type="text" class="form-control" id="editShow-price" value="${show.price}">
</div>
```

* add price to [`addShowForm`](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/src/javascripts/components/addShow/addShow.js#L19) form on **addShow.js**
```html 
<div class="form-group">
    <label for="addShow-price">Price</label>
    <input type="text" class="form-control" id="addShow-price">
</div>
```

* on **showList.js** add price to [`addShowEvent`](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/src/javascripts/components/showList/showList.js#L30)
```price: $('#addShow-price').val(),```

* on **showList.js** add price to [`editShowEvent`](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/src/javascripts/components/showList/showList.js#L58)
```price: $('#editShow-price').val(),```

**Comment by luketlancaster** [comment]
you did this one right @bnemchak? Like this issue can be closed out?
