### ISSUE TITLE
Add Price - Staff

### ISSUE THREAD

**Issue by bnemchak** [nss-evening-cohort-12/nutshell-elk#111]
# User
As a user, when I visit the staff page not logged in I should see rows of cards of each staff now including price. 
As a user, when I visit the staff page logged in I should see rows of cards of each staff now including price.

# AC
**WHEN** the user visits the staff section of the site via the homepage
**THEN** they should only see the available staff displayed
**AND** they will now see a price

**WHEN** the user is Logged-in they should see all of the staff displayed
**AND** there should also be a visible option to edit the staff and delete the staff
**AND** there should be a add staff button at the top of the page
**AND** they will now see a price

## dev notes
* add price to [seed data](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/db/staff.json) on **staff.json**
```js
"price": 75,
```

* add price to [`staffBuilders`](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/src/javascripts/components/buildStaff/buildStaff.js#L27) on  **buildStaff.js**
```js
price: $('#addStaff-price').val(),
```

* add price to [`editStaffEvent`](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/src/javascripts/components/buildStaff/buildStaff.js#L59) on  **buildStaff.js**
```js
price: $('#editStaff-price').val(),
```

* add price to [`showForm`](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/src/javascripts/components/addStaff/addStaff.js#L19) on **addStaff.js**
```js
<div class="form-group">
    <label for="addStaff-price">Price</label>
    <input type="text" class="form-control" id="addStaff-price">
  </div>
```

* add price to [`staffMakerAuth`](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/src/javascripts/components/buildStaff/buildStaffers.js#L19) on **buildStaffers.js**
```js
<h5 class="card-title">${staff.price}</h5>
```

* add price to [`staffMakerNoAuth`](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/src/javascripts/components/buildStaff/buildStaffers.js#L45) on **buildStaffers.js**
```js
<h5 class="card-title">${staff.price}</h5>
```

* add price to [`staffEditForm`](https://github.com/nss-evening-cohort-12/nutshell-elk/blob/master/src/javascripts/components/editStaff/editStaff.js#L22) on **editStaff.js**
```js
<div class="form-group">
        <label for="editStaff-price">Price</label>
        <input type="text" class="form-control" id="editStaff-price" value="${staff.price}">
      </div>
```

**Comment by luketlancaster** [comment]
this one too @bnemchak?
