### ISSUE TITLE
Ability to Edit a Food

### ISSUE THREAD

**Issue by jeaninedavis** [nss-evening-cohort-12/nutshell-elk#17]
# User Story
As a user, I should be able to edit my spellin' mistakes on Foods.

# AC
**WHEN** the logged in user visits the Foods section of the site via the homepage
**THEN** they should see all of the available foods on display
**AND** there should also be a visible option to edit the foods 
**AND** once they edit the item, it should be changed in the firebase database
**AND** they should see it change on the display when they hit the update button
**AND** if the user is not logged in, they should not see an option to edit

# Dev Notes
* create an `editFoods.js` file 
* use a `const getFoods` function and `axios.get` in `foodData.js` to obtain the foodId 
* easier option: use dataset or modal to bring up the edit form on the same page
* challenge option: inline editing within the table
* use this function in the `foodData.js` file:
```js
const updateFood = (foodId, editedFood) => axios.put(`${baseUrl}/foods/${foodId}.json`, editedFood);
```
* use bootstrap form to fill in data
```html
<form>
  <div class="form-group">
    <label for="food-name">Food name</label>
    <input type="text" class="form-control" id="food-name">
  </div>
  <div class="form-group">
    <label for="food-price">Price</label>
    <input type="text" class="form-control" id="food-price">
  </div>
<div class="form-group">
    <label for="food-imageUrl">Image Url</label>
    <input type="text" class="form-control" id="food-imageUrl">
  </div>
<div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Is Currently Available</label>
  </div>
  <button type="submit" class="btn btn-primary" id="food-editor">Update!</button>
</form>
```
* use a click event to show the edit form that takes the `foodId`
* use a click event to update the information from the edit form

**Comment by luketlancaster** [comment]
where are you gonna get the `foodId` from when you click on the update button?
