### ISSUE TITLE
Ability to Delete a Show

### ISSUE THREAD

**Issue by jeaninedavis** [nss-evening-cohort-12/nutshell-elk#30]
# User Story
As a user, I should be able to delete a staff member from the Renaissance Fair.

**WHEN** the logged-in user visits the Show section of the site via the homepage
**THEN** they should see all of the currently scheduled shows on display
**AND** there should be an button to delete shows on the page
**AND** if the user is not logged in, they should not see an option to delete

# Dev Notes
* in `showData.js` use Axios to delete staff from the firebase database
```js
const deleteShow = (showId) => axios.delete(`${baseUrl}/show/${showId}.json`);
```

**Comment by luketlancaster** [comment]
I think your delete method is wrong here? Shouldn't you be passing in a `showId` and `delete`-ing `/show/${showId}.json`?
