### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by wcampbell91** [nss-evening-cohort-12/nutshell-elk#32]
![Screen Shot 2020-07-13 at 9 24 57 PM](https://user-images.githubusercontent.com/62917622/87373505-683ae580-c54f-11ea-8a74-2f7d494fe072.png)

**Comment by luketlancaster** [comment]
1. You can probably take the user out of the ERD for now. There's no actual relationship between the user table and the other tables
1. Can you throw a bool column on food/souvenirs? Like `isAvailable` or `isStocked` or something?
1. Other than that looks good!
