### ISSUE TITLE
Site Style/Theme

### ISSUE THREAD

**Issue by jeaninedavis** [nss-evening-cohort-12/nutshell-elk#35]
# User Story
As a user, I need to see a b-e-a-utiful website

# AC
**WHEN** the user visits the site
**THEN** they should see a cohesive theme across the pages
**AND** it should be styled with good-looking fonts, colors, and images

# Dev Notes
* use https://coolors.co/a44200-75b8c8-f7e8a4-455f48-646b61 for color palette
* use Bootsrap, Sass, Fontawesome, and Google fonts
* consider https://unsplash.com/s/photos/castle
* fonts.google.com Fondamento font family for headers

**Comment by luketlancaster** [comment]
which color palette are you gonna use‽‽
