### ISSUE TITLE
# Bugs Found

### ISSUE THREAD

**Issue by MarkyAaronYoung** [nss-evening-cohort-12/nutshell-elk#89]
* user can't view food when logged out. User should be able to view food when logged out.

* uncaught error type

**Comment by bnemchak** [comment]
can't see food - same error logged in and logged out
![Screen Shot 2020-07-20 at 9 15 07 PM](https://user-images.githubusercontent.com/62910336/88005117-3802c200-cace-11ea-81a4-af722a43a796.png)

**Comment by bnemchak** [comment]
when click souvenirs - no open - same for logged in and logged out
![Screen Shot 2020-07-20 at 9 16 49 PM](https://user-images.githubusercontent.com/62910336/88005191-65e80680-cace-11ea-8f57-1d7147aa6489.png)

**Comment by bnemchak** [comment]
when click shows - no open -same for logged in and logged out
![Screen Shot 2020-07-20 at 9 19 15 PM](https://user-images.githubusercontent.com/62910336/88005309-b6f7fa80-cace-11ea-89ae-ae81671daaf5.png)

**Comment by bnemchak** [comment]
when click staff - no open- same for logged in and logged out
![Screen Shot 2020-07-20 at 9 19 54 PM](https://user-images.githubusercontent.com/62910336/88005335-cb3bf780-cace-11ea-920a-bbaac63d06fd.png)
