### ISSUE TITLE
# Add Events Collection

### ISSUE THREAD

**Issue by MarkyAaronYoung** [nss-evening-cohort-12/nutshell-elk#92]
## User Story
As a user, I should able to add events to my event page

## AC
**When** a user is authenticated
**Then** clicks on a "Add New Event" button
**Then** it should create a page container
**Where** I can add staff, souvenirs, food, and show items onto

## Dev Notes
* Create a landing page/container div for ```events.js```
* printToDom using ```#events-page```
* Create a single Create Event button
* Addclass.hide unless the user is logged in
* Create addEventForm() use bootstrap form bootstrap form
```src/javascripts/component/addEventForm/addEventForm.js```
* $('body').on('click', '.add-event-form', addEventForm)
Form will print to #new-event div using utils.printToDom('#new-event, domString); function
Create addEvent() that takes values from form and creates new event object
$('body').on('click', '.submit-event-form', addEvent)
* ```create axios.post()``` commands to firebase to add to data
* Dropdown example code, see [example](https://github.com/nss-evening-cohort-12/chatty-delta-narnia/blob/master/src/javascripts/components/navBar/navbar.js)

**Comment by MarkyAaronYoung** [comment]
<img width="493" alt="Screen Shot 2020-07-22 at 7 05 08 PM" src="https://user-images.githubusercontent.com/62973018/88241478-d702f780-cc4f-11ea-8c46-210e227e1c4d.png">

**Comment by MarkyAaronYoung** [comment]
**IGNORE THIS ONE**

<img width="509" alt="Screen Shot 2020-07-22 at 7 07 42 PM" src="https://user-images.githubusercontent.com/62973018/88241493-de2a0580-cc4f-11ea-8f44-8686b3d637e8.png">

**Comment by luketlancaster** [comment]
This dropdown is probably gonna be pretty complex, right? Given that you'll need to GET every collection that you have, and create dropdowns for those events? If that's the case I'd break this card in to several: displaying all events, adding an event, displaying a single event, etc

**Comment by luketlancaster** [comment]
oh yeah I see you have some cards for that now

**Comment by bnemchak** [comment]
<img width="388" alt="Screen Shot 2020-07-24 at 4 43 03 PM" src="https://user-images.githubusercontent.com/62910336/88437773-d3e14600-cdcc-11ea-8648-9ac7fdbd6bde.png">
