### ISSUE TITLE
# Delete Events Collection

### ISSUE THREAD

**Issue by MarkyAaronYoung** [nss-evening-cohort-12/nutshell-elk#93]
## User Story
As a user, I should be able to delete only the events I've created as well as delete souvenirs, shows, staff, and food items I've added to that event

## AC
**When** a user is authenticated
**And** Then they click on an event page
**Then** the user can delete an entire event 
**When** they click on a delete button on the specific event page

## Dev Notes
* create an event collection div
* AddClass.hide unless user is authenticated
* ```src/javascripts/components/deleteEvent/deleteEvent.js```
* ```src/javascripts/components/deleteEventItems/deleteEventItems.js```
*```$('body'). on('click', '.delete-event', deleteEvent)```
* Use axios.delete() to remove events from firebase. ```src/javascripts/helpers/data/eventData```

**Comment by luketlancaster** [comment]
this just removes the staff (and other things) from the event, right? Like it doesn't delete the Staff item totally?

**Comment by bnemchak** [comment]
<img width="343" alt="Screen Shot 2020-08-02 at 6 00 28 PM" src="https://user-images.githubusercontent.com/62910336/89134354-13551400-d4ea-11ea-8f64-213648bf6024.png">

**Comment by luketlancaster** [comment]
you'll also want axios requests to delete anything from any join tables you may have created
