### ISSUE TITLE
# Create Financial Reporting Page

### ISSUE THREAD

**Issue by MarkyAaronYoung** [nss-evening-cohort-12/nutshell-elk#94]
## User
As a user, I should be able to see a detail page for a specific event.

## AC
**When** a user is authenticated 
**And** clicks on a financial reporting button 
**That** is located on a specific event page
**Then** they will be taking to a financial reporting page for that specific event

## Dev Notes 
* create Financial Reporting landing page/div for ```finances.js```
* printToDom using #finances-page
* Create a ```Financial Reports``` button
* Addclass.hide unless the user is logged in
* ```src/javascripts/component/finances/finances.js```
$('body').on('click', '.finances-page, finances)
Form will print to ```#finances-page``` div using utils.printToDom('#finances-page, domString); function

**Comment by luketlancaster** [comment]
are there any wireframes for this?
