### ISSUE TITLE
# Read Events Page

### ISSUE THREAD

**Issue by MarkyAaronYoung** [nss-evening-cohort-12/nutshell-elk#95]
## User Story
As a user, I should be able to see(READ) entire Event with all the Staff, Food, Shows, and Souvenirs.

## AC
**When** a user is authenticated
**And** they click on the Event Page button
**Then** they can see a specific event
**And** all the Staff, Food, Shows, and Souvenirs added/pinned to that event

## Dev Notes
* Create a landing page/container div for ```events.js```
* ```src/javascripts/component/events.js```
* ```src/javascripts/components/eventsList.js```
* printToDom using ```#events-page```
* Create an Events Page button
* create `events.json`
```
name:
food:
show:
staff:
souvenirs:
cost:
```

* Addclass.hide unless the user is logged in
* create axios.put() commands to firebase to add to data

**Comment by bnemchak** [comment]
<img width="493" alt="Screen Shot 2020-07-22 at 7 05 08 PM" src="https://user-images.githubusercontent.com/62910336/88440877-e790aa80-cdd4-11ea-8b33-54bac658856f.png">

**Comment by MarkyAaronYoung** [comment]
<img width="390" alt="Screen Shot 2020-07-24 at 5 19 48 PM" src="https://user-images.githubusercontent.com/62973018/88606905-7acf1780-d043-11ea-8d3f-612767d05030.png">
