### ISSUE TITLE
# ERD

### ISSUE THREAD

**Issue by MarkyAaronYoung** [nss-evening-cohort-12/nutshell-elk#97]

**Comment by MarkyAaronYoung** [comment]
<img width="1036" alt="Screen Shot 2020-07-22 at 6 46 33 PM" src="https://user-images.githubusercontent.com/62973018/88240152-ec762280-cc4b-11ea-8bb6-355f44a7a759.png">

**Comment by luketlancaster** [comment]
So can each event have > 1 of the child entities? If so I think you'll have to do a join table 🤔 

also not sure what this finances table does for you here if each event only has one of each thing. couldn't you just get the one of each thing and add together the `price`? I think what you might want is something like

##### EventItem
column | type
--------|----
eventId | string
thingId | string
thingType | string

where `thingId` is the foodId and `thingType` is `foods` (so you could use that to fetch `${baseUrl}\${thingType}\${thingId}.json` or somesuch. That's just me noodling though...you'll need to think through that and figure out if it's gonna work for your requirements or not

**Comment by luketlancaster** [comment]
also: `thingId` and `thingType` are **terrible** names. Please, for the love of everything, come up with better ones if you need to go that direction

**Comment by bnemchak** [comment]
<img width="746" alt="Screen Shot 2020-07-25 at 9 25 11 AM" src="https://user-images.githubusercontent.com/62910336/88459150-c2458000-ce58-11ea-84d3-1f901bd68235.png">

**Comment by psihanorak** [comment]
![image](https://user-images.githubusercontent.com/61893644/88460022-d9876c00-ce5e-11ea-84d8-bbefd92aa08a.png)

**Comment by luketlancaster** [comment]
do y'all have an updated ERD with join tables?

**Comment by MarkyAaronYoung** [comment]
<img width="1161" alt="Screen Shot 2020-07-27 at 7 33 57 PM" src="https://user-images.githubusercontent.com/62973018/88605652-29715900-d040-11ea-92c0-50d23a3413d8.png">

**Comment by luketlancaster** [comment]
so are you going to have > 1 souvenir, food, show, and staff for each event?
